### ISSUE TITLE
Make Rx a peer dependency

### ISSUE THREAD

**Issue by basham** [pH200/cycle-react#21]
Leave it to the developer to manage RxJS versions, not this project. Move RxJS from `"dependencies"` to `"peerDependencies"` in `package.json`. See this issue for further rationale:
https://github.com/cyclejs/cycle-core/issues/174

Also note how `cycle-core` accepts any version of RxJS. Perhaps the same should be done here as well.
https://github.com/cyclejs/cycle-core/blob/v5.0.1/package.json#L23-L25

**Comment by basham** [comment]
Also note that Rx is removed from the `Cycle` object:
https://github.com/cyclejs/cycle-core/releases/tag/v5.0.0

Similarly, I don't see a need for a shortcut for either `Rx` or `React` in the main `cycle-react` `Cycle` object. They should be directly declared when used.
https://github.com/pH200/cycle-react/blob/v3.1.0/index.js

**Comment by pH200** [comment]
Agreed. And it doesn't seem like `rx` will change their API signature so we should be able to accept any version of `rx`. [ReactiveX/RxJS](https://github.com/ReactiveX/RxJS) is another story though.

Will release 4.0 with this fixed very soon.

**Comment by pH200** [comment]
Fixed in 4.0.0
