### ISSUE TITLE
refs do not actually work 3.1.0

### ISSUE THREAD

**Issue by corps** [pH200/cycle-react#23]
I just created a pull with a test that demonstrates the issue and a potential fix:  https://github.com/pH200/cycle-react/pull/22

Despite changes to the readme and the warning for using vtree functions, 3.1.0 will still throw errors if your components use refs because that JSX is constructed outside of Render.  The reason why the tests pass now is that the observer is only producing a single value with Observer.just, which will work because that will happen to coincide with the ReactDOM.render that initially constructs and attaches the component, but fails for any subsequent rendering.

Let me know what your thoughts are on this approach.

**Comment by pH200** [comment]
That's a good find. Let's fix this and release 4.0.

A few things I'm concerned about:

1. So refs still require some extra setup. It's either we provide a scheduler for the component or we accept the function type for the view result. Which do you prefer? Roll back to use functions looks easier but scheduler will have more flexibility.
2. If we're going for the scheduler. I will prefer to put it into the parameters of the component function:
```js
function component(props, interactions, self, lifecycles, renderScheduler) {
  return Observable
    .timer(50)
    .map(() => <h3>some stuff</h3>)
    .observeOn(renderScheduler);
}
```

That's one more extra parameter. And it's hard to say whether that's more or less intuitive compared to 2.0:

```js
function component(props, interactions, self) {
  return Observable
    .timer(50)
    .map(() => () => <h3>some stuff</h3>);
}
```

3. Good job in the ReactRenderScheduler. However, I've noticed some spots that can be polished:
  - Using utils.inherits would be just fine IMO
  - Don't use `delete`, it breaks V8's optimization, use array like queue for collecting the scheduled actions
  - _scheduleFuture can be removed

**Comment by corps** [comment]
Scheduler vs function wrapper:

This is probably the first question that should be answered, and it's tricky.  I went back and forth on the approach (though to be honest I wrote the scheduler in part just to learn more about schedulers in RxJs :P)

Pros for 2.0 approach:
* No additional code, simple
* No additional parameters passed to components
Cons for 2.0 approach:
*  Makes composition of Observables of React elements trickier (If I want to build different parts of the component in different observables, I have to combine "functions of" observables together and be wary of when they are called.)
*  Typing is confusing (Someone may not understand why sometimes the observable is of functions and other times its of elements)

Pros to Scheduler approach:
*  Very general.  The scheduler can also be used to batch work inside of the render call (if say, other react magic depends on the stack timing)
*  Observables are always of elements, typing is more clear, composition simpler.
*  Is more obvious what is going on.  When I first see delay(0, renderScheduler) I have a better understanding of what is happening than a map(() => () => Observable.just(blah)).
Cons to Scheduler approach:
*  More code and complexity.
*  Additional parameters
*  Schedulers are not a universally understood tool within the RxJS toolbox.

Based on that, I'm willing to contribute moving forward, but I'd like to hear yours or anyone else's thoughts.

**Comment by corps** [comment]
I'm almost inclined to ask for /both/ approaches to coexist.

The function wrapper is "simpler" for some large percentage of use cases.
The scheduler is more powerful and general for composition.

Thoughts?

**Comment by pH200** [comment]
Thats' some great analysis.

I'm rolling back the function wrapper and put the Scheduler feature to a new branch ([render-scheduler](https://github.com/pH200/cycle-react/tree/render-scheduler)). There are several thing we need to fix before merging this into master:

- `_scheduleFuture` could be failed if it's disposed before `setTimeout` has invoked the inner function
- Tests
- Documentations

**Comment by corps** [comment]
Sounds good.  I have some further minor adjustments to the scheduler, and some tests, in an incomplete branch off my fork.  I'll sync back to you my work in the next couple of days.

**Comment by corps** [comment]
Working on a new pull request based off your concerns and the new branch.

**Comment by corps** [comment]
Alright, see https://github.com/pH200/cycle-react/pull/24

**Comment by pH200** [comment]
Fixed and merged. Thanks!

By the way, I've changed the `delay(0, renderScheduler)` to `observeOn(renderScheduler)` in the tests and docs. It works the same but I think it's a better API to call in this case.
