### ISSUE TITLE
Missing react-dom in installation guide of README

### ISSUE THREAD

**Issue by rayshih** [pH200/cycle-react#27]
Currently:

`npm install cycle-react react rx`

Should add `react-dom`, right?

**Comment by jackypan1989** [comment]
yup, v0.14.x use react-dom

**Comment by pH200** [comment]
Well, I think it's pretty straightforward react-dom is a dependency as it shown in the example, so I would probably not change this line to make it longer. Besides, there might be some library which uses react but not react-dom in the future.
