### ISSUE TITLE
The div element will crash react native app while the first event of props is very slow.

### ISSUE THREAD

**Issue by rayshih** [pH200/cycle-react#28]
As I observed,
If the first event (which will transform into view) is slow, then the cycle component will return `<div />` first.
But react native have no such element. so it will crash.

Although, I can use `startWith` to fix the slow props problem.

**Comment by pH200** [comment]
Yes, you should always make sure that there is at least a initial element available for the observable.

However, Cycle-React should give you an empty view even for react-native. I am not familiar with react-native TBH. Any suggestions fixing this?

**Comment by pH200** [comment]
Closed. The task for adding default element for react-native is tracked in the backlog https://github.com/pH200/cycle-react/projects/1#card-2414384

**Comment by rayshih** [comment]
I can always utilize the `options.rootTagName`, so the problem is I need to do this every time I want to create a component. And doing so is very cumbersome.

I currently use the `startWith` solution as I mentioned above, but this means every component will be rendered twice. And I can check every component and remove the unnecessary `startWith`, but the app may become much more fragile.

I think we need a way to inject the setting to framework layer from the very beginning.

https://github.com/pH200/cycle-react/blob/master/index.js#L41

Instead of:

```
component: createComponent(React, RxAdapter)
```

I purpose: 

```
component_: defaultOption => createComponent(React, RxAdapter, defaultOption),
component: createComponent(React, RxAdapter) // maybe keep this for backward compatibility.
```

Also, FYI, the react native now using `React` from `react` package instead of `react-native`, so you can remove the `./native.js` file entirely.

**Comment by pH200** [comment]
I agree that exposing the function of `createComponent` is a good idea. But, I guess you can write the following code for the time being:

```js
import {component as originalComp} from 'cycle-react'
import {View} from 'react-native'

function component(name, definitionFn, options={rootComponent: View}) {
  return originalComp(name, definitionFn, options)
}

const Item = component(/* as before */) 
```

By the way, the right name for this option is `rootTagName`. And that still works, though, because we're just passing the value to `React.createElement`. Maybe we should rename this parameter to `rootElementType`.

And thanks for the information about react-native :)
