### ISSUE TITLE
support  RxJs5?

### ISSUE THREAD

**Issue by franckXu** [pH200/cycle-react#29]
support  RxJs5?

 I modified  node_modules/rx/index.js require

``` javascript
var Rx = require('@reactivex/rxjs')
module.exports = Rx;
```

error log 

``` javascript
Uncaught TypeError: Object prototype may only be an Object or null: undefined
inherits @ inherits_browser.js:5
MakeReactRenderScheduler @ react-render-scheduler.js:13
(anonymous function) @ react-render-scheduler.js:109
```

**Comment by vp2177** [comment]
Hi, just curious if RxJS v5 is supported now or is support planned?

**Comment by pH200** [comment]
@vp2177 Hello, RxJS v5 is not supported currently. But, it shouldn't be difficult to support it right now comparing to last year's RxNext. I'll implement the adaptor for that.

**Comment by pH200** [comment]
You can now find RxJS 5 support in branch `rxjs` https://github.com/pH200/cycle-react/tree/rxjs

I still have to change documentation and examples before publishing it. And notice that we may deprecate props.get with [pluck](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-pluck).

**Comment by vp2177** [comment]
Excellent, thank you! I'll give it a try. And I agree, `pluck` is the way to go.

**Comment by pH200** [comment]
Implemented in v6.
