### ISSUE TITLE
Earthquake in Southern Taiwan

### ISSUE THREAD

**Issue by corps** [pH200/cycle-react#31]
Hi @ph200,

There is no private messaging on github, so I apologize for the weird issue.

I wanted to let you know that I recently visited Taipei, Taiwan and had an amazing time.  But after I left, I heard about the very big earthquake in southern Taiwan.  I hope you and your family is safe, and that no one you know was hurt.  Sending my thoughts!

**Comment by pH200** [comment]
I am still in one piece. It was lunar new year so I wasn't around here. Thanks a lot for your care!
