### ISSUE TITLE
any example for async fetch remote data?

### ISSUE THREAD

**Issue by geohuz** [pH200/cycle-react#32]
Or can I integrate the cycle-httpdriver into the cycle-react directly?

Thanks

**Comment by pH200** [comment]
You can integrate the cycle-httpdriver which would involve some setup with Observable. It's a little bit tricky and I must write an example for this.

Or, you can use any request library which returns a promise and join it into your observable chain.

Example:

https://github.com/cycle-react-examples/cycle-react-examples.github.io/blob/master/ajax/ajax.js
http://cycle-react-examples.github.io/ajax/index.html
